[terminal.shell]
program = "/usr/bin/fish"
args = ["--login"]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMonoNL Nerd Font" }
bold = { family = "JetBrainsMonoNL Nerd Font" }
italic = { family = "JetBrainsMonoNL Nerd Font" }
size = 9

# [colors.primary]
# foreground = "#eeeeee"
# background = "#3b224c"
#
# [colors.normal]
# black = "#181818"
# red = "#ac4242"
# green = "#90a959"
# yellow = "#f4bf75"
# blue = "#6a9fb5"
# magenta = "#aa759f"
# cyan = "#75b5aa"
# white = "#d8d8d8"

[colors.primary]
foreground = "#ebeafa"
background = "#3b224c"

[colors.selection]
foreground = "#eaeaea"
background = "#404040"

[colors.normal]
black = "#3b224c"
red = "#f47868"
green = "#9ff28f"
yellow = "#efba5d"
blue = "#a4a0e8"
magenta = "#dbbfef"
cyan = "#6acdca"
white = "#ebeafa"

[colors.bright]
black = "#697c81"
red = "#ff3334"
green = "#9ec400"
yellow = "#e7c547"
blue = "#7aa6da"
magenta = "#b77ee0"
cyan = "#54ced6"
white = "#ffffff"

[window]
padding.x = 4
padding.y = 4
decorations = "None"

[keyboard]
bindings = [
    { key = "F11", action = "ToggleFullscreen" },
    { key = "Insert", mods = "Shift", action = "Paste" },
    { key = "Insert", mods = "Control", action = "Copy" },
]

[terminal]
