[colors.primary]
foreground = "#ebeafa"
background = "#3b224c"

[colors.selection]
foreground = "#eaeaea"
background = "#404040"

[colors.normal]
black = "#3b224c"
red = "#f47868"
green = "#9ff28f"
yellow = "#efba5d"
blue = "#a4a0e8"
magenta = "#dbbfef"
cyan = "#6acdca"
white = "#ebeafa"

[colors.bright]
black = "#697c81"
red = "#ff3334"
green = "#9ec400"
yellow = "#e7c547"
blue = "#7aa6da"
magenta = "#b77ee0"
cyan = "#54ced6"
white = "#ffffff"

