[colors.primary]
background = '#181216'
foreground = '#ecdfe5'

[colors.selection]
text = '#ecdfe5'
background = '#67355d'

[colors.cursor]
text = '#181216'
cursor = '#f4b2e2'

[colors.normal]
black   = '#181216'
red     = '#d75c3c'
green   = '#6ed681'
yellow  = '#d1db7b'
blue    = '#c75aa9'
magenta = '#b78fac'
cyan    = '#f4b2e2'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e0795f'
green   = '#86e096'
yellow  = '#e0e897'
blue    = '#ffbff2'
magenta = '#b158a8'
cyan    = '#a9638c'
white   = '#ffffff'
